AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Backend for Bible Contexto

Parameters:
  env:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Resources:
  Selector:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: selector
      Handler: app.handler
      Runtime: python3.9
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          BACKEND_BUCKET: !Ref BackendBucket
      Policies:
        - Version: "2012-10-17"
          Statement:
          - Effect: Allow
            Action: 
              - s3:ListBucket
            Resource: 
              - !Sub "arn:${AWS::Partition}:s3:::${BackendBucket}/*"
      Events:
        WordOfTheDay:
          Type: Schedule
          Properties:
            Schedule: cron(0 5 * * ? *)

  Generator:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: generator
      Handler: app.handler
      Runtime: python3.9
      MemorySize: 2048
      Timeout: 90
      Environment:
        Variables:
          BACKEND_BUCKET: !Ref BackendBucket
      Policies:
        - Version: "2012-10-17"
          Statement:
          - Effect: Allow
            Action: 
              - s3:PutObject
            Resource: 
              - !Sub "arn:${AWS::Partition}:s3:::${BackendBucket}/*"

  BackendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${env}-bible-contexto-backend"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - "*"
            AllowedMethods:
              - GET
            AllowedHeaders:
              - "*"
            MaxAge: 3000

  BackendBucketBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref BackendBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Join ["", ["arn:aws:s3:::", !Ref BackendBucket, "/*"]]
