AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Backend for the Prayer Request App

Parameters:
  env:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Resources:
  App:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      Runtime: python3.9
      MemorySize: 2048
      Timeout: 300
      Environment:
        Variables:
          BACKEND_BUCKET: !Ref BackendBucket
      Policies:
        - Version: "2012-10-17"
          Statement:
          - Effect: Allow
            Action: 
              - s3:PutObject
            Resource: 
              - !Sub "arn:${AWS::Partition}:s3:::${BackendBucket}/*"

  BackendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${env}-bible-contexto-backend"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  BackendBucketBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref BackendBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Join ["", ["arn:aws:s3:::", !Ref BackendBucket, "/*"]]
